services:
  ytdl_material:
    build:
      context: .
    environment:
      write_ytdl_config: "true"
    volumes:
      - appdata:/app/appdata
      - ./audio:/app/audio
      - ./video:/app/video
      - ./subscriptions:/app/subscriptions
      - ./users:/app/users
    ports:
      - "8998:17442"
    image: lzpreslav/youtubedl-material:latest
volumes:
  appdata:
